# Created using wingetcreate 0.5.0.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.1.0.schema.json

PackageIdentifier: tristanheaven.GTKHash
PackageVersion: 1.4.1
PackageLocale: en-US
Publisher: tristanheaven
PackageName: GTKHash
License: GPL v2
ShortDescription: A cross-platform desktop utility for computing message digests or checksums.
ManifestType: defaultLocale
ManifestVersion: 1.1.0

